package com.ccacic.financemanager.controller;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javafx.scene.layout.Pane;

/**
 * Holds frame factories mapped to their names and acts as an interface for
 * interacting with them
 * @author Cameron Cacic
 *
 * @param <T> the type of the frame factories
 */
public abstract class FXFrameContainer<T> {

	protected final Map<String, FXFrameFactory<T>> frameListMap;
	
	/**
	 * Creates a new container
	 */
	protected FXFrameContainer() {
		frameListMap = new HashMap<>();
	}
	
	/**
	 * Adds the frame factory to this container
	 * @param factory the factory to add
	 */
	public void addFrameFactory(FXFrameFactory<T> factory) {
		frameListMap.put(factory.getFactoryName(), factory);
	}
	
	/**
	 * Returns the frame list generated by the factory found at the
	 * provided key
	 * @param key the key to the factory to use
	 * @param toEdit the item to pass to the factory
	 * @return a List of frames created by the factory
	 */
	public List<FXPopupProgActivityFrame<?, ? extends Pane>> getFrameList(String key, T toEdit) {
		FXFrameFactory<T> factory = frameListMap.get(key);
		if (factory == null) {
			return new ArrayList<>();
		}
		return factory.createFrameList(toEdit);
	}
	
}
